name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: CI Build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Build
      run: ./gradlew test

#    - name: Code Coverage Report
#      uses: irongut/CodeCoverageSummary@v1.3.0
#      with:
#        filename: ./build/reports/jacoco/test/jacocoTestReport.xml
#        badge: true
#        fail_below_min: true
#        format: markdown
#        hide_branch_rate: false
#        hide_complexity: true
#        indicators: true
#        output: both
#        thresholds: '60 80'
#
#    - name: Add Coverage PR Comment
#      uses: marocchino/sticky-pull-request-comment@v2
#      if: github.event_name == 'pull_request'
#      with:
#        recreate: true
#        path: code-coverage-results.md

    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.3
      with:
        paths: ./build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
